### ISSUE TITLE
Parser gets confused with some parentheses

### ISSUE THREAD

**Issue by davidmontemayor** [dzannotti/vscode-babel#3]
Seems like some parentheses are being incorrectly identified as something else. Here's the same line, one that calls a function inside an object and another that calls a top level function:

![screenshot 2016-05-25 18 36 49](https://cloud.githubusercontent.com/assets/340216/15558385/b22d01b8-22a7-11e6-9223-b866a5dd5fe1.png)

Clearly the one that's invoking a top level function is not being parsed properly.

**Comment by dzannotti** [comment]
The parser produces `token js meta function-call with-arguments punctuation definition parameters begin` which i think is correct in this context. I think it's down a to a theming issue. Will investigate further, thanks for the report!

**Comment by davidmontemayor** [comment]
It's possible, the current theme seemed to work for all the other cases though, I'll investigate in my theme.

**Comment by dzannotti** [comment]
I did investigate, the parser seems to work as intended
