### ISSUE TITLE
All functions / methods are underlined

### ISSUE THREAD

**Issue by alex-pex** [dzannotti/vscode-babel#5]
Hello!

I use "Flatland Monokai" color scheme and all function are underlined. It also underlines React component. I have the same problem with the "Monokai" color scheme included in vscode, but not "Monokai dimmed" or default color scheme.

I don't know if you can do anything about it. Maybe you put a flag on methods which triggers a different coloration?

**Comment by dzannotti** [comment]
Sadly the coloring it's up to the theme, this plugin only provides the parsing side of things
